site :opscode

cookbook 'apt','2.3.8'
cookbook 'erlang', '1.4.2'
cookbook 'yum', '3.1.4'
cookbook 'yum-epel', '0.3.4'
cookbook 'yum-erlang_solutions', '0.2.0'
cookbook 'build-essential', '1.4.2'
cookbook 'galera', '0.4.1'
cookbook 'rabbitmq', '3.0.4'
cookbook 'ganglia', '0.1.1'
cookbook 'graphite', '0.4.8'
cookbook 'haproxy', '1.6.4'
cookbook 'keepalived', '1.2.0'
